version: '3.3'

services:
  ct-pos-web:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    image: php:7.4-fpm
    container_name: ct-pos-web
    links:
      - ct-pos-db
    depends_on:
      - ct-pos-db
    networks:
      - ct-pos-project
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www

  ct-pos-webserver:
    image: nginx:alpine
    container_name: ct-pos-webserver
    depends_on:
      - ct-pos-web
    networks:
      - ct-pos-project
    ports:
      - '81:80'
      - '445:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    domainname: local.ct-pos.backend
    hostname: local.ct-pos.backend

  ct-pos-db:
    image: mysql:5.7
    container_name: ct-pos-db
    restart: unless-stopped
    tty: true
    env_file: ./.env
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - ct-pos-project
    volumes:
      - ct-posDBDate:/var/lib/mysql/

#Docker Networks
networks:
  ct-pos-project:
    driver: bridge

#Volumes
volumes:
  ct-posDBDate:
    driver: local
